version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432" # Expose PostgreSQL port
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  address_service:
    build:
    container_name: address_service
    ports:
      - "5002:80" # Map port 5002 on the host to port 80 in the container
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=mydb;Username=myuser;Password=mypassword

